apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: argo-tunnel
  name: argo-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-tunnel
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argo-tunnel
    spec:
      containers:
      - image: gcr.io/stackpoint-public/argot:0.5.2
        imagePullPolicy: Always
        name: argo-tunnel
        command: ["/argot"]
        args:
        - --v=2
        - --ingressClass=argo-tunnel
        - --namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: argo-tunnel
              topologyKey: kubernetes.io/hostname