name: cloudflare-ingress-controller

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat .version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }}
            --tag raspbernetes/argo-tunnel:${{ github.sha }} \
            -f ./Dockerfile \
            . \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }}
            --tag raspbernetes/argo-tunnel:latest \
            --tag raspbernetes/argo-tunnel:${{ env.VERSION }} \
            -f ./Dockerfile \
            . \
            --push
